Added FormAPI::getInstance();
jojoe77777/FormAPI pull request #33
Opened 2018-06-11 22:58 UTC by UramnOIL

2018-06-12 10:37 UTC, SOF3 commented
What prevents you from using `$server->getPluginManager()->getPlugin("FormAPI")`?

2018-06-12 10:38 UTC, JackMD commented
Laziness

2018-06-12 10:57 UTC, dktapps commented
lol no generics

2018-06-12 10:59 UTC, SOF3 commented
Then why not `return Server::getInstance()->getPluginManager()->getPlugin("FormAPI")` instead of maintaining your own singleton?

2018-06-12 10:59 UTC, SOF3 requested changes

2018-06-12 10:59 UTC, SOF3 commented on src/jojoe77777/FormAPI/FormAPI.php
> +    /** @var FromAPI */
typo here

2018-06-13 12:12 UTC, UramnOIL commented
Oh my god, I totally forgot 'Server::getInstance()'...
Please forgive my mistake:(

2018-06-13 12:15 UTC, UramnOIL commented
That's certainly laziness lol

2018-06-14 10:47 UTC, jojoe77777 commented
Unneeded as stated above

2018-06-14 10:47 UTC, closed without merging